Add fail if.es6.js does not exist when it should

diff --git a/pre-commit-8-4 b/pre-commit-8-4
--- a/pre-commit-8-4
+++ b/pre-commit-8-4
@@ -110,6 +110,13 @@ for FILE in $FILES; do
               echo -e "${red}FAILURE${reset} $FILE has changed but $BASENAME.es6.js has not"
               STATUS=1
             fi
+          else
+            # If there is no .es6.js file then there should be unless the .js is
+            # not really Drupal's.
+            if ! [[ "$FILE" =~ ^core/assets/vendor ]] ; then
+              echo -e "${red}FAILURE${reset} $FILE does not have a corresponding $BASENAME.es6.js"
+              STATUS=1
+            fi
           fi
         fi
         # @todo Check that the corresponding .js file has been updated
